### ISSUE TITLE
Want pickupAt datapoint for FedEx and UPS at least

### ISSUE THREAD

**Issue by sepatel** [mediocre/bloodhound#24]
Both UPS and FedEx provide a Pickup datapoint (code of PU) which indicates when the package was picked up. This data point is often times not the same thing as the shippedAt datapoint due to package first having to goto the facilities first.

Can we get added to the response data an additional datapoint called pickupAt which is the timestamp of when the PU event took place for FedEx and UPS at least?

**Comment by freshlogic** [comment]
I'd be in favor of making this event the source of the `shippedAt` timestamp if we're 100% sure it indicates a physical tender of the shipment and not just a digital event that doesn't indicate a physical tender. If you have some sample tracking numbers we can take a look (or submit a PR).

**Comment by sepatel** [comment]
I'll get you dozens of examples on Monday if you like but the reason I didn't suggest changing the shippedAt is because it looked currently like it was refering for both UPS and FedEx at the times when the package left the Facilities to head towards the target destination. We do have at least 7 verbally confirmed cases of when the customer said it was picked up matching with actual FedEx/UPS pickup times but would have no way to prove that it would be 100%. I just have those 7 confirmations that stated the shippedAt time we specified was wrong is all (what we currently use).

I don't see the shippedAt as being a bad thing, seems kinda useful to know when it first departed from the carrier towards the final destination. The pickup time is when it was picked up from the carrier to be brought to the facility and while usually they appear to be within a few hours I can also imagine scenarios where they might span days (would need to look at some 5 to 7 day shipments or non-priority style deliveries to see).

I'll try to get a PR together around this early next week.
