### ISSUE TITLE
Support FedEx master tracking number

### ISSUE THREAD

**Issue by sepatel** [mediocre/bloodhound#29]
We have come across scenarios like tracking number 7083472863
https://www.fedex.com/apps/fedextrack/?tracknumbers=7083472863

The number being tracked is 10 digits long (master tracking number) that links 5 packages together (4 other normal tracking numbers are associated to the 4 other packages in the bundle). However, the master tracking number which should be pulling back information for all 5 tracking info.

Currently the code does not even recognize it as a fedex tracking number it looks like.

**Comment by sepatel** [comment]
Quick little snippet of code to demonstrate

```
const Bloodhound = require('@mediocre/bloodhound');

const bloodhound = new Bloodhound();

['7083472863', '397414590114', '397414590125', '397414590136', '397414590147'].forEach(tracking => {
    let carrier = bloodhound.guessCarrier(tracking);
    console.log(tracking, carrier);
});
```

Output
```
7083472863 undefined
397414590114 FedEx
397414590125 FedEx
397414590136 FedEx
397414590147 FedEx
```

**Comment by sepatel** [comment]
I should also mention that fedex officially refers to this concept as MPS (Multi Piece Shipment). UPS's equivalent is Master Tracking Number iirc.

**Comment by sepatel** [comment]
Hey @freshlogic, now that holidays are over, I wanted to bring this particular issue to light a bit more as it is something we have noticed issue with in production and while we have a hack in place to override the bloodhound implementation, I'd prefer to not have custom hacks in place to work around the issue if possible.

The MPS numbers for FedEx do not follow the normal validation rules but are valid tracking numbers for fedex. Our hack simply says that if it is a 10 digit number starting with 7, allow it to go through the normal FedEx flow.

**Comment by freshlogic** [comment]
Hey @sepatel.

MPS numbers aren't something we actively use here at [Mediocre](https://mediocre.com) but I'm not against adding some kind of support to Bloodhound for them. We have a pile of other projects we're working on though so I can't commit to a timeline for implementation. I'd personally devote some time to reviewing/merging a pull request if others wanted to take the time to dive into it.

Happy New Year!
